import bcrypt from 'bcryptjs';
const data = {


  users: [
    {
      name: 'Mbe',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Aba',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Tulips bouquet',
      slug: 'tulips-bouquet',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 0,

      rating: 4.5,
      numReviews: 10,
      description: 'white tulips bouquet',
    },
    {
      name: 'Lilies bouquet',
      slug: ' lilies-bouquet',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,

      rating: 4.0,
      numReviews: 10,
      description: 'white lilies bouquet',
    },
    {
      name: 'Roses bouquet',
      slug: 'roses-bouquet',

      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,

      rating: 4.5,
      numReviews: 14,
      description: 'pink roses bouquet',
    },
    {
      name: 'Roses bouquet2',
      slug: 'roses-bouquet2',

      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,

      rating: 4.5,
      numReviews: 14,
      description: 'pink roses bouquet',
    },
    {
      name: 'Pions bouquet',
      slug: 'pions-bouquet',

      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,

      rating: 4.5,
      numReviews: 10,
      description: 'pink pions bouquet',
    },
  ],
flowers : [
  {
    name: "Rose",
    slug: "rose",
    image: '/images/p6.jpg',
    images: ['/images/p4.jpg'],
    color: "Red",
    size: "Medium",
    description: "Beautiful red rose",
    price: 10,
    countInStock: 10,
    rating: 4.5,
    numReviews: 8,
  },
  {
    name: "Lily",
    slug: "lily",
    image: '/images/p5.jpg',
    images: ['/images/p3.jpg'],
    color: "White",
    size: "Large",
    description: "Elegant white lily",
    price: 12,
    countInStock: 15,
    rating: 4.8,
    numReviews: 12,
  },
  {
    name: "Tulip",
    slug: "tulip",
    image: '/images/p4.jpg',
    images: ['/images/p4.jpg'],
    color: "Red",
    size: "Medium",
    description: "Beautiful red rose",
    price: 10,
    countInStock: 10,
    rating: 4.5,
    numReviews: 8,
  },
  {
    name: "Pion",
    slug: "pion",
    image: '/images/p5.jpg',
    images: ['/images/p3.jpg'],
    color: "White",
    size: "Large",
    description: "Elegant white lily",
    price: 12,
    countInStock: 15,
    rating: 4.8,
    numReviews: 12,
  },
  {
    name: "Sunflower",
    slug: "sunflower",
    image: '/images/p4.jpg',
    images: ['/images/p8.jpg'],
    color: "Yellow",
    size: "Large",
    description: "Bright and cheerful yellow sunflower",
    price: 8,
    countInStock: 20,
    rating: 4.6,
    numReviews: 10,
  },
  {
    name: "Daisy",
    slug: "daisy",
    image: '/images/p5.jpg',
    images: ['/images/p10.jpg'],
    color: "White",
    size: "Small",
    description: "Delicate and charming white daisy",
    price: 6,
    countInStock: 25,
    rating: 4.3,
    numReviews: 7,
  },
  {
    name: "Orchid",
    slug: "orchid",
    image: '/images/p4.jpg',
    images: ['/images/p12.jpg'],
    color: "Purple",
    size: "Medium",
    description: "Exotic and graceful purple orchid",
    price: 15,
    countInStock: 12,
    rating: 4.9,
    numReviews: 15,
  },
  {
    name: "Carnation",
    slug: "carnation",
    image: '/images/p5.jpg',
    images: ['/images/p14.jpg'],
    color: "Pink",
    size: "Small",
    description: "Lovely pink carnation with delicate petals",
    price: 7,
    countInStock: 18,
    rating: 4.4,
    numReviews: 9,
  },
  {
    name: "Hvozdika",
    slug: "hvozdika",
    image: '/images/p5.jpg',
    images: ['/images/p14.jpg'],
    color: "Pink",
    size: "Small",
    description: "Lovely pink carnation with delicate petals",
    price: 7,
    countInStock: 18,
    rating: 4.4,
    numReviews: 9,
  },
],
  packings : [
    {
      name: 'Wrapping paper',
      price: 20,
      slug: 'wrapping-paper',
      countInStock: 100,
      rating: 4.5,
      numReviews: 10,

      image: '/images/p5.jpg',
    },
    {
      name: 'Box',
      price: 20,
      slug: 'box',
      image: '/images/p5.jpg',
      countInStock: 50,
      rating: 4.7,
      numReviews: 8,

    }
  ],
  orders: [
    {
      orderItems: [
        {
          slug: 'roses-bouquet',
          name: 'Sample Product 2',
          quantity: 1,
          image: 'sample-image-2.jpg',
          price: 15,
          product: '6643d04f4cd481cb59b0b5e4',
        },
      ],
      shippingAddress: {
        fullName: 'Jane Smith',
        address: '456 Elm Street',
        city: 'Los Angeles',
      },
      paymentMethod: 'PayPal',
      paymentResult: {
        id: 'payment-id-2',
        status: 'Paid',
        update_time: '2024-05-14',
      },
      itemsPrice: 15,
      shippingPrice: 3,
      totalPrice: 18,
      user: '6643d04f4cd481cb59b0b5e4',
      isPaid: true,
      paidAt: new Date(),
      isDelivered: true,
      deliveredAt: new Date()
    },
    {
      orderItems: [
        {
          slug: 'roses-bouquet',
          name: 'Sample Product 1',
          quantity: 2,
          image: 'sample-image-1.jpg',
          price: 10,
          product: '6643d04f4cd481cb59b0b5e4',
        },
      ],
      shippingAddress: {
        fullName: 'John Doe',
        address: '123 Main Street',
        city: 'New York',
      },
      paymentMethod: 'Credit Card',
      paymentResult: {
        id: 'payment-id-1',
        status: 'Paid',
        update_time: '2024-05-14',
      },
      itemsPrice: 20,
      shippingPrice: 5,
      totalPrice: 25,
      user: '6643d04f4cd481cb59b0b5e4',
      isPaid: true,
      paidAt: new Date(),
      isDelivered: false
    }
  ],
};
export default data;
